### PR TITLE
Add copier

### PR DESCRIPTION
**Pull request by Yajo**
Alternative to https://github.com/vinta/awesome-python/pull/1350

## What is this Python project?

A tool to create projects from templates.

## What's the difference between this Python project and similar ones?

Here's a comprehensive comparison: https://www.recallstack.icu/en/2020/04/18/yeoman-and-cookiecutter-are-dead-long-live-copier/

--

Anyone who agrees with this pull request could vote for it by adding a :+1: to it, and usually, the maintainer will merge it when votes reach **20**.

### CODE REVIEW

**Comment by Enetrati** [comment]
Your link is dead. So do you have an alternative link with explanation on why copier should added to this list?

**Comment by Yajo** [comment]
My link is not dead AFAICS, just yesterday the server was down for maintenance.

**Comment by Enetrati** [comment]
I am not really convinced in the usage of Copier.

Based on the info on the website I do not see the extra relevancy compared to Cookiecutter.

From a technical point:
 - Okay. You don't need to use logic. Great.
But what I want to use logic? Is that still possible? No.
- Cookiecutter has standard support for specific extra options like SMTP libraries, gunicorn configuration. Etc.
There is nothing to be found in the documentation.

Also is the bashing towards Cookiecutter like having no funds (based on a old post from 2017) doesn't make it more worth it to use Copier. Quite the opposite.

I'm not a Cookiecutter fan. But I believe there needs more work to be done to make Copier actually awesome.

**Comment by Yajo** [comment]
>  But what I want to use logic? Is that still possible?

yes, and it doesn't need to be written in python.



> Cookiecutter has standard support for specific extra options like SMTP libraries, gunicorn configuration. Etc.

:roll_eyes: Sorry but I don't understand this sentence. It's like saying you don't like bananas because they don't sound loud... what cookiecutter are you talking about? I speak about https://github.com/cookiecutter/cookiecutter and it has nothing to do with smtp or gunicorn... 

> Also is the bashing towards Cookiecutter like having no funds (based on a old post from 2017) doesn't make it more worth it to use Copier. Quite the opposite.

I think that's the least important point in all this :grin: 

---

OK, see some more reasons taken [from here](https://github.com/pykong/copier#cookiecutter):

> You configure your template in copier.yml instead of cookiecutter.json.

Writing JSON by hand should be a crime these days. Cookiecutter has no solution for that since 4 years ago: https://github.com/cookiecutter/cookiecutter/issues/970

Considering all JSON files are valid YAML files, this says not so much in favor of that project's maintenance.

> Copier has very useful features that are missing in Cookiecutter (or require extra software), like the ability to **update a generated project** when the original template changes, and to run **migrations** when updating.

This is awesome. Completely awesome. Blows away any other template engine out there.

Cookiecutter has no solution for this, since 2016 this time: https://github.com/cookiecutter/cookiecutter/issues/784 and https://github.com/cookiecutter/cookiecutter/issues/1004

**Comment by Yajo** [comment]
> But I believe there needs more work to be done to make Copier actually awesome.

Oh BTW this is true. But today it already has killer features. :relaxed:

**Pull request merged**
